### ISSUE TITLE
not_found

### ISSUE THREAD

**Issue by eneroth** [warrant-dev/edge-agent#19]
Hi! I'm trying to run the edge client locally, on a mac.

The only thing I have in `agent.properties` is `API_KEY=<the actual API key>`

I'm greeted by the following error:

```
❯ docker run --name edge-agent --env-file agent.properties --platform linux/amd64 --network host warrantdev/edge-agent
2023/07/20 13:39:35 Edge server serving authz requests on port 3000
2023/07/20 13:39:35 Intializing edge client...
2023/07/20 13:39:36 Unable to initialize edge client.
2023/07/20 13:39:36 HTTP 404 {"code":"not_found","message":"Endpoint /v1/expand not found","type":"Endpoint","key":"/v1/expand"}
```

Please help.

**Comment by eneroth** [comment]
OK, so I realize now that this might be a very obscure way of saying "your plan does not include access to the edge client". 

Is there anyway I can evaluate this without jumping to a paid plan?

**Comment by kkajla12** [comment]
> Is there anyway I can evaluate this without jumping to a paid plan?

Hi @eneroth, currently there is no way of trying out the edge agent without being on a paid plan. We're considering offering a trial period of one of our paid plans to new free-tier customers, at which point it will be possible to test out the edge agent. If you're interested, I can reach out to you once that work is completed.

Also, I'd like to invite you to join our [Slack community](https://join.slack.com/t/warrantcommunity/shared_invite/zt-12g84updv-5l1pktJf2bI5WIKN4_~f4w) where we regularly announce new features/updates like this. We can also discuss your use case and requirements in more depth there and see if we can come up with other solutions for you.

**Comment by kkajla12** [comment]
Hi @eneroth, I've gone ahead and enabled edge agent support in your account now so you can evaluate it. Can you try setting up / starting up an edge agent again?

**Comment by eneroth** [comment]
@kkajla12 Sorry for the belated response (vacations). Thank you! I will try it out promptly!

**Comment by eneroth** [comment]
@kkajla12 I'm making progress in that the Edge client starts up without error codes, but I'm having trouble connecting to it.

The output from the client reads:
```
=> docker run --name edge-agent --env-file agent.properties --platform linux/amd64 --network host warrantdev/edge-agent
2023/08/08 09:48:29 Intializing edge client...
2023/08/08 09:48:29 Edge server serving authz requests on port 3000
2023/08/08 09:48:29 Edge client initialized.
2023/08/08 09:48:29 Connecting to https://stream.warrant.dev/v1
```

However, the Java client reports
```
Execution error (ClosedChannelException) at sun.nio.ch.SocketChannelImpl/ensureOpen (SocketChannelImpl.java:202).
```

I've initialized the client with a base URL of `"http://localhost:3000"`.


I get a similar connection refused error when doing a POST to `"http://localhost:3000/v1/authorize"`.

**Comment by kkajla12** [comment]
Hi @eneroth,

1. It looks like the `--network host` flag is no longer supported in Docker Desktop for Mac, so try running the Docker container with this command instead (we're manually mapping port 3000 of the container to port 3000 of localhost):
```bash
docker run --name edge-agent --env-file agent.properties --platform linux/amd64 -p 3000:3000 warrantdev/edge-agent
```

2. Our Java SDK did not have support for the edge agent, but we've added support to help you move forward. Please upgrade to `v3.1.0` of the Java SDK and follow the steps [here](https://github.com/warrant-dev/warrant-java#configuring-api-endpoints) to configure the SDK's check endpoint to be your local edge agent.

I hope that helps. Let me know if that works and/or if you run into any other issues.

**Comment by eneroth** [comment]
@kkajla12 Thank you! With your suggestions, it's now up and running. Here's the results of my load test:

```
Evaluation count : 56700 in 60 samples of 945 calls.
             Execution time mean : 1,017724 ms
    Execution time std-deviation : 42,590283 µs
   Execution time lower quantile : 927,789828 µs ( 2,5%)
   Execution time upper quantile : 1,101596 ms (97,5%)
                   Overhead used : 1,927932 ns
```

So it averages out at 1ms for the check suggested in the introductory tutorial. 

So with the Edge Agent, the latency no longer presents a barrier to entry for us. My next step will be modelling a simple use case from our actual domain model and performing some checks on that. With this baseline, I'm much more confident that Warrant is a realistic alternative.

Thank you again!

**Comment by akajla09** [comment]
@eneroth that sounds good. Feel free to reach out if you need any help modeling your object types/use case.
