### ISSUE TITLE
Allow users to configure the DB number

### ISSUE THREAD

**Issue by trashhalo** [warrant-dev/edge-agent#38]
Looks like the agent is hard coded to use DB 1. It would be nice if users had some control over that if they were already using 1.

**Comment by kkajla12** [comment]
@trashhalo, we just released [`v1.4.0`](https://hub.docker.com/layers/warrantdev/edge-agent/v1.4.0/images/sha256-c7437992f85d539c5de2c70f5d094dc7bb3ce6919d26634d15b3bb03678f3849?context=explore) of the edge agent with support for a new `REDIS_DATABASE` property that allows you to configure this. You can read more about it [here](https://docs.warrant.dev/quickstart/edge-agent/).
